---
title: "QuickDraw Time"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggjoy)
library(stringr)
library(forcats)
```

```{r}
metafile <- './quickdraw classification.csv'
meta <- read_csv(metafile, skip = 1)
name_parts <- str_split_fixed(meta$name, coll("."), 2)
meta$basename <- name_parts[, 1]
```

```{r}
bugs <- meta %>% filter(bug == TRUE)
```


```{r}
filename <- 'data/dog.stats.csv'
dogs_org <- read_csv(filename)
```

```{r}
filename <- 'data/cat.stats.csv'
cats_org <- read_csv(filename)
```

## Clean Data



```{r}
prepare_data <- function (data) {
  new_data <- data %>% mutate(drawing_time_seconds = drawing_time / 1000, drawing_time_draw_seconds = drawing_time_draw / 1000, drawing_time_pause_seconds = drawing_time_pause / 1000)
  
  new_data <- new_data %>% 
    # a few have time values not in incremental
    filter(stroke_in_order == 0) %>% 
    # a few have weird times
    filter(drawing_time_min >= 0) %>% 
    filter(drawing_time_max > 0) %>%
    filter(drawing_time_draw > 100)
  return(new_data)
}
```


```{r}
dogs <- prepare_data(dogs_org)
cats <- prepare_data(cats_org)
```


```{r}
dogs %>% filter(recognized == 'True') %>% 
  ggplot(aes(x = drawing_time_draw_seconds)) +
  geom_histogram(binwidth = 1) + 
  labs(title = "Histogram of Dog Drawing Time")
```

```{r}
dogs %>% filter(recognized == 'True') %>%  filter(drawing_time_draw_seconds < 25) %>%
  ggplot(aes(x = drawing_time_draw_seconds)) +
  geom_histogram(binwidth = 1, fill = "#607d8b") +
  theme_light() +
  labs(title = "Histogram of Dog Drawing Time")
```


```{r}
dogs %>% filter(recognized == 'True') %>%  filter(drawing_time_draw_seconds < 25) %>%
  ggplot(aes(x = drawing_time_draw_seconds, y = (..count..)/sum(..count..))) +
  geom_histogram(binwidth = 5, fill = "#607d8b") +
  theme_light() +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(limits = c(0,20)) +
  labs(title = "", y = "", x = "")
```

```{r}
dogs %>% 
  ggplot(aes(x = drawing_time_draw_seconds, fill = recognized)) +
  geom_histogram(binwidth = 1) + 
  labs(title = "Histogram of Dog Drawing Time")
```


```{r}
cats %>% filter(recognized == 'True') %>% 
  ggplot(aes(x = drawing_time_draw_seconds)) +
  geom_histogram(binwidth = 1) + 
  labs(title = "Histogram of Cat Drawing Time")
```

```{r}
dogs_cats <- rbind(dogs, cats)
```

```{r}
dogs_cats %>% filter(drawing_time_draw_seconds <= 20) %>%
  ggplot(aes(x = drawing_time_draw_seconds, y = word))+
  geom_joy(scale = 4) + theme_joy() +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0, 0))
```


```{r}
dogs_cats_rec_sum <- dogs_cats %>% group_by(word, recognized) %>% summarise(count = n()) %>% mutate(freq = count / sum(count))
```


```{r}
dogs_cats_rec_sum %>%
  ggplot(aes(x = word, y = freq, fill = recognized)) +
  geom_bar(stat = "identity")
```



```{r}
cats_rec <- cats %>% filter(recognized == 'True')
dogs_rec <- dogs %>% filter(recognized == 'True')
```

```{r}
dogs_cats_rec <- rbind(dogs_rec, cats_rec)
```

```{r}
dogs_cats_rec %>%
  ggplot(aes(x = word, y = drawing_time_pause_seconds)) +
  geom_boxplot()
```

```{r}
summary(dogs_rec$drawing_time_pause_seconds)
summary(cats_rec$drawing_time_pause_seconds)
```


```{r}
#dogs_cats <- rbind(cat_drawings_rec, dog_drawings_rec)
```


```{r}
ggplot() +
  geom_histogram(data = cats_rec, aes(x = drawing_time_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'red', binwidth = 1) +
  geom_histogram(data = dogs_rec, aes(x = drawing_time_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'blue', binwidth = 1) +
  scale_x_continuous(limits = c(0, 30)) + 
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribution of Total Seconds Taken for Drawing a cat vs a dog", y = "", x = "Drawing Time (sec)")
  
```


```{r}
dogs_cats %>% filter(drawing_time_seconds > 20) %>% count()
dogs_cats %>% filter(drawing_time_seconds > 20) %>% count() / nrow(dogs_cats)
```

```{r}
summary(dogs_rec$drawing_time_seconds)
summary(cats_rec$drawing_time_seconds)
```


```{r}
dogs_cats %>% filter(drawing_time_seconds > 20) %>%
  ggplot(aes(x = word, y = drawing_time_pause_seconds)) + 
  geom_boxplot()
```


```{r}
ggplot() +
  geom_histogram(data = cats_rec, aes(x = drawing_time_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'red', binwidth = 1) +
  geom_histogram(data = dogs_rec, aes(x = drawing_time_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'blue', binwidth = 1) +
  scale_x_continuous(limits = c(0, 25)) + 
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribution of Total Seconds Taken for Drawing a cat vs a dog", y = "", x = "Drawing Time (sec)")
  
```

```{r}
 p<- ggplot() +
  geom_histogram(data = cats_rec, aes(x = drawing_time_draw_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'red', binwidth = 1, center = 0, closed = 'left') +
  geom_histogram(data = dogs_rec, aes(x = drawing_time_draw_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'blue', binwidth = 1, center = 0, closed = 'left') +
  scale_x_continuous(limits = c(0, 25), breaks = c(0,1,2,3,4,5,6,7,8,9,10)) + 
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribution of Drawing Seconds Taken for Drawing a cat vs a dog", y = "", x = "Drawing Time (sec)")
pg <- ggplot_build(p)
pg
```


```{r}
dogs_rec <- dogs_rec %>% mutate(time_bin = floor(drawing_time_draw_seconds))
dog_bins <- dogs_rec %>% group_by(time_bin) %>% summarise(count = n()) %>% mutate( freq = count / sum(count))
```

```{r}
cats_rec <- cats_rec %>% mutate(time_bin = floor(drawing_time_draw_seconds))
cat_bins <- cats_rec %>% group_by(time_bin) %>% summarise(count = n()) %>% mutate( freq = count / sum(count))
```

```{r}
dog_bins %>%
  ggplot() + 
  geom_bar(data = dog_bins, mapping = aes(x = time_bin, y = freq), stat='identity', fill = 'blue', alpha = 0.6) + 
  geom_bar(data = cat_bins, mapping = aes(x = time_bin, y = freq), stat='identity', fill = 'red', alpha = 0.6) + 
  scale_x_continuous(limits=c(0, 25))
```


## Sample Data

Test if the different n sizes affecting data.

```{r}
cats_rec_sample <- cats_rec %>% sample_n(50000)
dogs_rec_sample <- dogs_rec %>% sample_n(50000)
```


```{r}
  ggplot() +
  geom_histogram(data = cats_rec_sample, aes(x = drawing_time_draw_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'red', binwidth = 1) +
  geom_histogram(data = dogs_rec_sample, aes(x = drawing_time_draw_seconds, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'blue', binwidth = 1) +
  scale_x_continuous(limits = c(0, 25)) + 
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribution of Drawing Seconds Taken for Drawing a cat vs a dog", y = "", x = "Drawing Time (sec)")
```

## Pause Time

```{r}
  ggplot() +
  geom_histogram(data = cats_rec, aes(x = drawing_time_pause / 1000, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'red', binwidth = 1) +
  geom_histogram(data = dogs_rec, aes(x = drawing_time_pause / 1000, y = (..count..)/sum(..count..)), alpha = 0.6, fill = 'blue', binwidth = 1) +
  scale_x_continuous(limits = c(0, 25)) + 
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribution of Pause Seconds Taken for Drawing a cat vs a dog", y = "", x = "Drawing Time (sec)")
```



```{r}
mean(cats_rec$drawing_time_seconds)
mean(dogs_rec$drawing_time_seconds)
```


```{r}
mean(cats_rec$drawing_time_draw_seconds)
mean(dogs_rec$drawing_time_draw_seconds)
```


```{r}
mean(cats_rec$stroke_count)
mean(dogs_rec$stroke_count)
```

```{r}
dogs_rec %>% filter(drawing_time_draw_seconds < 30) %>%
  ggplot(aes(x = drawing_time_draw_seconds, y = stroke_count)) +
  geom_point(alpha = 1 / 100)
  
```

```{r}
cats_rec %>%
  ggplot(aes(x = drawing_time_draw_seconds, y = stroke_count)) +
  geom_point(alpha = 1 / 10)
  
```

```{r}
cats_rec %>% filter(drawing_time_pause_seconds < 20) %>%
  ggplot(aes(x = drawing_time_pause_seconds, y = stroke_count)) + 
  geom_point(alpha = 1 / 10) +
  geom_smooth(method='lm')
```

```{r}
cats_rec_filtered <- cats_rec %>% filter(drawing_time_pause_seconds < 20)

```

```{r}
fit <- lm(drawing_time_pause_seconds ~ stroke_count , data = cats_rec_filtered)
summary(fit)
```



```{r}
countrycodes_dogs <- dogs_rec %>% group_by(countrycode) %>% summarise(country_count = n()) %>% arrange(-country_count)
countrycodes_cats <- cats_rec %>% group_by(countrycode) %>% summarise(country_count = n()) %>% arrange(-country_count)
```

```{r}
top_countrycodes <- countrycodes_dogs %>% head(n = 30)
```

```{r}
dogs_rec_top_countries <- dogs_rec %>% filter(countrycode %in% top_countrycodes$countrycode)

dogs_rec_top_countries <- dogs_rec_top_countries %>% left_join(top_countrycodes, by = "countrycode")
```

```{r}
dogs_rec_top_countries %>% filter(drawing_time_draw_seconds < 30) %>%
  ggplot(aes(x = drawing_time_draw_seconds)) +
  facet_wrap(~ countrycode) +
  geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]), binwidth = 1) 
```

```{r}
dogs_rec_top_countries %>% filter(drawing_time_draw_seconds < 30) %>%
  ggplot(aes(x = drawing_time_draw_seconds)) +
  facet_wrap(~ countrycode) +
  geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]), binwidth = 1) 
  
```


```{r}
dogs_rec_top_countries %>% filter(drawing_time_pause_seconds < 15) %>%
  ggplot(aes(x = drawing_time_pause_seconds)) +
  facet_wrap(~ countrycode) +
  geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]), binwidth = 1) 
  
```


# Category sub-sections

```{r}
read_names <- function (names) {
  data_path <- './data/'
  all_cates <- vector("list", nrow(names))  
  
  for(i in 1:nrow(names)) {
    name_file <- names[i, "basename"]
    full_path <- paste(data_path, name_file, ".stats.csv", sep='')
    name <- read_csv(full_path)
    all_cates[[i]] <- name
  }
  
  all_cates_df <- do.call("rbind", all_cates)
  
  all_cates_df_clean <- prepare_data(all_cates_df)

  all_cates_df_clean_rec <- all_cates_df_clean %>% filter(recognized == 'True')
  
  return(all_cates_df_clean_rec)
  
}
```

```{r}
all_bugs_df <- read_names(bugs)
```

```{r}
bugs_agg <- all_bugs_df %>% group_by(word) %>% summarise(count = n(),
            stroke_count_mean = mean(stroke_count),
            stroke_count_med = median(stroke_count),
            drawing_time_pause_sec_mean = mean(drawing_time_pause_seconds), 
            drawing_time_pause_sec_med = median(drawing_time_pause_seconds), 
            drawing_time_draw_sec_mean = mean(drawing_time_draw_seconds), 
            drawing_time_draw_sec_med = median(drawing_time_draw_seconds)) %>%
  arrange(-drawing_time_draw_sec_mean)
```


```{r, fig.height=6, fig.width=4}
all_bugs_df %>% 
ggplot(aes(x = drawing_time_draw_seconds, y = factor(word, levels = bugs_agg$word), fill = factor(word, levels = bugs_agg$word))) +
geom_joy(size = 0.55 ) +
  theme_joy() +
  scale_x_continuous(limits=c(1, 20), expand = c(0.01, 0)) +
  scale_y_discrete(expand = c(0.01, 0)) + 
  scale_fill_brewer(guide = FALSE, palette = "Greys", direction = -1) + 
  labs(title = 'Bugs', x = '', y = '')
ggsave('bugs.png', width = 8, height = 12)
```

```{r, message=FALSE}
fruits <- meta %>% filter(fruit == TRUE)
all_fruits <- read_names(fruits)
```

```{r}
fruits_agg <- all_fruits %>% group_by(word) %>% summarise(count = n(),
            stroke_count_mean = mean(stroke_count),
            stroke_count_med = median(stroke_count),
            drawing_time_pause_sec_mean = mean(drawing_time_pause_seconds), 
            drawing_time_pause_sec_med = median(drawing_time_pause_seconds), 
            drawing_time_draw_sec_mean = mean(drawing_time_draw_seconds), 
            drawing_time_draw_sec_med = median(drawing_time_draw_seconds)) %>%
  arrange(-drawing_time_draw_sec_mean)
```


```{r, fig.height=6, fig.width=4}
all_fruits %>% 
ggplot(aes(x = drawing_time_draw_seconds, y = factor(word, levels = fruits_agg$word), fill = factor(word, levels = fruits_agg$word))) +
geom_joy(size = 0.55 ) +
  theme_joy() +
  scale_x_continuous(limits=c(1, 20), expand = c(0.01, 0)) +
  scale_y_discrete(expand = c(0.01, 0)) + 
  scale_fill_brewer(guide = FALSE, palette = "Oranges", direction = -1) + 
  labs(title = 'Fruits', x = '', y = '')
ggsave('fruits.png', width = 8, height = 12)
```

```{r}
all_fruits %>% filter(word == "banana") %>%
  ggplot(aes(x = drawing_time_draw_seconds)) +
  geom_histogram(binwidth = 0.1) + 
  scale_x_continuous(limits = c(0, 20))
```


```{r}
all_fruits %>% filter(word == "banana") %>%
  ggplot(aes(x = drawing_time)) +
  geom_histogram(binwidth = 100) +
  scale_x_continuous(limits = c(0, 20000))
```

```{r}
all_fruits %>% filter(word == "banana") %>%
  ggplot(aes(x = stroke_count)) +
  geom_histogram(binwidth = 1) 
  #scale_x_continuous(limits = c(0, 20))
```



```{r}
bananas <- all_fruits %>% filter(word == "banana")
```

```{r}
bananas$round_time <- round(bananas$drawing_time_seconds, 1)
```


```{r}
bananas %>%
  ggplot(aes(x = round_time )) +
  geom_histogram(binwidth = 0.1) +
  scale_x_continuous(limits = c(0.5, 8))

```


```{r}
bananas %>% filter(round_time < 20) %>%
  ggplot(aes(x = round_time, y = stroke_count)) +
  geom_point()
```

```{r}
bananas_by_time <- bananas %>% group_by(round_time, stroke_count) %>% summarise(n = n()) %>% mutate(freq = n / sum(n))
```

```{r}
bananas_by_time %>% filter(round_time < 20) %>% filter(stroke_count < 10) %>%
  ggplot(aes(x = round_time, fill = factor(stroke_count), y = freq)) +
  geom_bar(stat = 'identity')
```



```{r, message=FALSE}
animals_meta <- meta %>% filter(animal == TRUE)
all_animals <- read_names(animals_meta)

library(RColorBrewer)
```

```{r}
animals_agg <- all_animals %>% group_by(word) %>% summarise(count = n(),
            stroke_count_mean = mean(stroke_count),
            stroke_count_med = median(stroke_count),
            drawing_time_pause_sec_mean = mean(drawing_time_pause_seconds), 
            drawing_time_pause_sec_med = median(drawing_time_pause_seconds), 
            drawing_time_draw_sec_mean = mean(drawing_time_draw_seconds), 
            drawing_time_draw_sec_med = median(drawing_time_draw_seconds)) %>%
  arrange(-drawing_time_draw_sec_mean)
```

```{r, fig.height=6, fig.width=4}
all_animals %>% 
ggplot(aes(x = drawing_time_draw_seconds, y = factor(word, levels = animals_agg$word), fill = factor(word, levels = animals_agg$word))) +
geom_joy(size = 0.55 ) +
  theme_joy() +
  scale_x_continuous(limits=c(1, 18), expand = c(0.01, 0)) +
  scale_y_discrete(expand = c(0.01, 0)) + 
  #scale_fill_brewer(guide = FALSE, palette = "YlGnBu", direction = -1) + 
  scale_fill_manual(values=rep(brewer.pal(6,"GnBu"),times=9), guide = FALSE) +
  labs(title = 'Animals', x = '', y = '')
ggsave('animals.png', width = 8, height = 12)
```


```{r, message=FALSE}
all_cates <- read_names(meta)
```


```{r}
all_agg <- all_cates %>% group_by(word) %>% summarise(n = n(),
            scount_me = mean(stroke_count),
            scount_md = median(stroke_count),
            d_pause_me = mean(drawing_time_pause_seconds), 
            d_pause_md = median(drawing_time_pause_seconds), 
            d_draw_me = mean(drawing_time_draw_seconds), 
            d_draw_md = median(drawing_time_draw_seconds),
            d_total_md = median(drawing_time_seconds),
            d_total_me = mean(drawing_time_seconds)) %>%
  arrange(-d_draw_me)
```


```{r}
all_agg %>%
  ggplot(aes(x = drawing_time_draw_sec_mean, y = drawing_time_draw_sec_med)) +
  geom_point()
```

```{r}
library(ggbeeswarm)
```


```{r}
all_agg %>% 
  ggplot(aes(x = drawing_time_draw_sec_med, y = '')) + 
  geom_beeswarm(groupOnX = FALSE, cex=2.8, size = 2) +
  labs(x = '', y = '')
  #geom_quasirandom(groupOnX = FALSE, varwidth = TRUE)
  
```

```{r}
write_csv(all_agg, 'all_aggregates.csv')
```


# All Categories

```{r}
data_path <- './data/'
stat_files <- list.files(path = data_path, pattern = '\\.stats\\.csv')
length(stat_files)
all_cates <- vector("list",length(stat_files))
length(all_cates)
```


```{r, message=FALSE, warning=FALSE}
for(i in 1:length(stat_files)) {
  stat_file <- stat_files[i]
  full_path <- paste(data_path, stat_file, sep='')
  print(full_path)
  cate_org <- read_csv(full_path)
  cate <- prepare_data(cate_org)
  all_cates[[i]] <- cate
  
}
```


```{r}
all_cates_df <- do.call("rbind", all_cates)
```

```{r}
all_cates_df_clean <- prepare_data(all_cates_df)
```


```{r}
all_cates_df_clean_rec <- all_cates_df_clean %>% filter(recognized == 'True')
```



```{r}
all_cates_mean <- all_cates_df_clean_rec %>% group_by(word) %>% 
  summarise(count = n(),
            stroke_count_mean = mean(stroke_count),
            stroke_count_med = median(stroke_count),
            drawing_time_pause_sec_mean = mean(drawing_time_pause_seconds), 
            drawing_time_pause_sec_med = median(drawing_time_pause_seconds), 
            drawing_time_draw_sec_mean = mean(drawing_time_draw_seconds), 
            drawing_time_draw_sec_med = median(drawing_time_draw_seconds)) %>%
  arrange(-drawing_time_draw_sec_mean)
```


```{r, fig.height=6, fig.width=4}

all_cates_df_clean_rec$word <- factor(all_cates_df_clean_rec$word, levels = all_cates_df_clean_rec$word[order(all_cates_df_clean_rec$word)])


all_cates_df_clean_rec %>% filter(drawing_time_draw_seconds <= 20) %>%
  ggplot(aes(x = drawing_time_draw_seconds, y = word ))+
  geom_joy(scale = 4) + theme_joy()
```


```{r}
all_cates_df %>% filter(word == 'dog') %>% count()
```




```{r}
all_cates_df_clean_rec %>% filter(word == 'dog') %>% filter(drawing_time_draw_seconds <= 20) %>%
 ggplot(aes(x = drawing_time_draw_seconds)) +
  geom_histogram(binwidth = 1) + 
  labs(title = "Histogram of Drawing Time")
```

